# simulation
strategy = "octree"
scenario = "ring"
integrator = "verlet"
duration = 50
timestep = 1e-2
output_interval = 5e-1
nozmom = false
num_bodies = 1024
seed = 42

# output 
csv_output = "results/ring.csv"
msgpack_output = "results/ring.msgpack"

# visualization
viz = true
viz_show_orbits = false
viz_speed_factor = 1.0
viz_trail_length = 1.0
viz_trail_segments = 10
viz_size_scale = 100.0
viz_size_min = 8.0
viz_size_max = 32.0
viz_orbit_width = 3.0
viz_camera_center = [0.0, 0.0, 0.0]
viz_camera_distance = 35.0
viz_camera_rotation = [-0.6, 0.0, 0.0]
viz_show_octree = false