# simulation
strategy = "brute_force"
scenario = "simple"
integrator = "verlet"
duration = 250
timestep = 1e-2
output_interval = 5e-1
nozmom = false
# num_bodies = 0
# seed = 42

# output 
csv_output = "results/simple.csv"
msgpack_output = "results/simple.msgpack"

# visualization
viz = true
viz_show_orbits = true
viz_speed_factor = 10.0
viz_trail_length = 2.0
viz_trail_segments = 50
viz_size_scale = 10.0
viz_size_min = 8.0
viz_size_max = 32.0
viz_orbit_width = 3.0
viz_camera_center = [0.0, 0.0, 0.0]
viz_camera_distance = 100.0
viz_camera_rotation = [-0.5, 0.0, 0.0]
viz_show_octree = false